### ISSUE TITLE
Error in multiparts documents when partnums attribute is specified

### ISSUE THREAD

**Issue by aplatanado** [owenh000/asciidoctor-multipage#24]
The problem can be reproduced, adding `:partsnum:` to the preamble of the test document `basic-multipart.adoc`:

~~~~
= Basic Multipart Test
:doctype: book
:toc: left
:partnums:
~~~~

and running the tests afterwards:

~~~~
$ bundler exec rake test

...

  1) Error:
AsciidoctorMultipageTest#test_black_box_docs:
NoMethodError: undefined method `divmod' for "I":String
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/helpers.rb:262:in `block in int_to_roman'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/helpers.rb:261:in `each'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/helpers.rb:261:in `map'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/helpers.rb:261:in `int_to_roman'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:98:in `sectnum'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:500:in `convert_section'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/converter/html5.rb:55:in `convert'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/abstract_block.rb:75:in `convert'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:513:in `block in convert_section'    
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:510:in `delete_if'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:510:in `convert_section'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/converter/html5.rb:55:in `convert'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/abstract_block.rb:75:in `convert'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:223:in `block in convert_document'   
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:220:in `delete_if'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:220:in `convert_document'
    /..../asciidoctor-multipage/lib/asciidoctor-multipage.rb:252:in `convert_embedded'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/converter/html5.rb:63:in `convert'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/document.rb:948:in `convert'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:118:in `convert'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:190:in `block in convert_file'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:190:in `open'
    /..../asciidoctor-multipage/vendor/bundle/ruby/2.7.0/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:190:in `convert_file'
    /..../asciidoctor-multipage/test/test_asciidoctor-multipage.rb:16:in `block in test_black_box_docs'
    /..../asciidoctor-multipage/test/test_asciidoctor-multipage.rb:10:in `foreach'
    /..../asciidoctor-multipage/test/test_asciidoctor-multipage.rb:10:in `test_black_box_docs'
...

~~~~

I think the error is caused by [lib/asciidoctor-multipage.rb#L98](https://github.com/owenh000/asciidoctor-multipage/blob/26ccb4e86c006588389dc4540b977e0cbd6d0967/lib/asciidoctor-multipage.rb#L98) because @numeral already is in roman numbers when sectnum() method is called in part sections.

I fixed it, changing the line to:

~~~~
%(#{@numeral}#{append})
~~~~

Now all test pass.

**Comment by owenh000** [comment]
@aplatanado, thanks for the report and fix! I have applied this in commit 910ac435af06a26027a0dcc1ea9aeb076c92783f and I plan to include it in a release soon.
