### ISSUE TITLE
Unable to generate multipage document with doctype article

### ISSUE THREAD

**Issue by plevold** [owenh000/asciidoctor-multipage#6]
When compiling this minimal example: 

```asciidoc
= Sample Document
Author Name
:doctype: article
:toc: center
:sectnums:


== Level 2

Some text goes here

=== Level 3

other text goes here
```

with the command `asciidoctor -r asciidoctor-multipage -b multipage_html5 -D out sample.adoc --trace` I get the following output:

```
Traceback (most recent call last):
        20: from /usr/local/bin/asciidoctor:23:in `<main>'
        19: from /usr/local/bin/asciidoctor:23:in `load'
        18: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/bin/asciidoctor:15:in `<top (required)>'
        17: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:113:in `invoke!'
        16: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:113:in `each'
        15: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:130:in `block in invoke!'
        14: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:189:in `convert_file'
        13: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:189:in `open'
        12: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:189:in `block in convert_file'
        11: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:117:in `convert'
        10: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
         9: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:84:in `convert'
         8: from /home/palle/.gem/ruby/2.7.0/gems/asciidoctor-multipage-0.0.3/lib/asciidoctor-multipage.rb:190:in `convert_document'
         7: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
         6: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:84:in `convert'
         5: from /home/palle/.gem/ruby/2.7.0/gems/asciidoctor-multipage-0.0.3/lib/asciidoctor-multipage.rb:124:in `convert_document'
         4: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:218:in `convert_document'
         3: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:88:in `convert'
         2: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/converter.rb:389:in `convert'
         1: from /home/palle/.gem/ruby/2.7.0/gems/asciidoctor-multipage-0.0.3/lib/asciidoctor-multipage.rb:393:in `convert_outline'
/home/palle/.gem/ruby/2.7.0/gems/asciidoctor-multipage-0.0.3/lib/asciidoctor-multipage.rb:247:in `generate_outline': undefined method `level' for nil:NilClass (NoMethodError)
```

If I remove the line `:toc: center` I don't get any error, but the link from `sample.html` to Level 2 as an incorrect href: `<a href="#_level_2">Level 2</a>`. This should rather be `<a href="_level_2.html">Level 2</a>`

I'm using the following gem versions:
```
asciidoctor (2.0.12, 2.0.10)
asciidoctor-multipage (0.0.3)
```

**Comment by owenh000** [comment]
Thanks for the report! This is fixed by commit a49cd05272c442c22f9b98b76c577e1a93a05b74, which is included in v0.0.5.
